# -*- coding: utf-8 -*-

from . import project_project
from . import project_task
from . import project_task_type
from . import project_update
from . import project_project_stage

WAITING_TASK_STAGE = '10'
TODO_TASK_STAGE = '15'
WAITING_FILE_TASK_STAGE = '20'
FILE_RECEIVED_TASK_STAGE = '25'
WAITING_DETAILS_TASK_STAGE = '30'
IN_PREPARATION_TASK_STAGE = '40'
IN_PROGRESS_TASK_STAGE = '50'
WAITING_QTY_TASK_STAGE = '60'
BAT_CLIENT_TASK_STAGE = '70'
TERMINATED_TASK_STAGE = '80'
CANCELED_TASK_STAGE = '90'

STUDIES_DELIVERY_TASK = '30'
PROJECT_NAME_TASK = '20'
DELIVERY_INFOS_TASK = '80'
FULLFILLEMENT_TASK = '85'

DRAFT_PROJECT_STAGE = '10'
PLANIFIED_PROJECT_STAGE = '20'
IN_PROGRESS_PROJECT_STAGE = '30'
DELIVERY_PRESTA_PROJECT_STAGE = '40'
DELIVERY_PROJECT_STAGE = '50'
LIVERY_PROJECT_STAGE = '60'
ROUTING_PROJECT_STAGE = '70'
EXTRACTION_PROJECT_STAGE = '80'
TERMINATED_PROJECT_STAGE = '90'
CANCELED_PROJECT_STAGE = '100'
TEMPLATE_PROJECT_STAGE = '140'
